# Generated by Django 2.1.5 on 2020-06-25 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='status',
            new_name='aprovado',
        ),
    ]
